In [2]:
import pandas as pd

In [3]:
data_files = ['EN_train.csv', 'ES_train.csv', 'YO_train.csv','ZH_train.csv']
df = pd.concat(
  (pd.read_csv(filename) for filename in data_files), 
  ignore_index=True
)

In [4]:
df

,Unnamed: 0,text,label,PET
0,0,We're just getting back what was TAKEN from us...,1,tinkle
1,1,I think AB390 will pass next year now that the...,1,tinkle
2,2,"Spooked by Rick Perry and Newt Gingrich, he st...",1,undocumented immigrants
3,3,"There is some good news. In June this year, Pr...",1,undocumented immigrants
4,4,Romney declared himself @ @ @ @ @ @ @ @ @ @ ga...,1,undocumented immigrants
...,...,...,...,...
7754,2000,两个人终于走到谈婚论嫁的地步。 看着他们的全家福，小编真心羡慕!在洪欣、张丹峰两人相差11岁...,1,高龄
7755,2001,（漫文来源于网络）推荐阅读：【孕妈宝典】当[PET_BOUNDARY]高龄[PET_BOUN...,1,高龄
7756,2002,原标题：九旬老太卖祖屋养老六旬不孝子闹上法庭信息时报讯（记者魏徽徽）祖籍韶关、现年已经90岁...,1,高龄
7757,2003,在七十年代的《茶馆》演出中，五十多岁的胡宗温挑战剧中15岁的康顺子一角，将这个几乎没有台词的...,1,高龄
7758,2004,【概要】老人前几天刚被接过来住，疑似不慎从自家窗户跌出邻居介绍：儿女们都很孝顺，坠楼时家人可...,1,高龄

In [5]:
df.to_csv('multi_train.csv')